name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        node_version: [18.2.0, 16.17.0]  # Specify the Node.js versions you want to test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
